services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: node:20
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      set -eux &&
      npm install &&
      npm run prisma:migrate &&
      npm run prisma:seed
      "
    environment:
      DATABASE_URL: postgres://devuser:devpassword@postgres:5432/devdb
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
