name: Playwright Tests

# https://zenn.dev/k2wanko/articles/60c195cc4bff0a

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/bake-action@v6
      with:
        push: false
        files: docker-compose.yml
        targets: app
    - name: Run Playwright tests in Docker container
      run: docker-compose run --rm app

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
