name: Playwright Tests

# https://zenn.dev/k2wanko/articles/60c195cc4bff0a

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/bake-action@v6
      with:
        load: true
        push: false
        files: compose.yaml
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
    - name: Run Playwright tests in Docker container
      run: docker compose run --rm app
