name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: Cache apt archives
      id: cache-apt
      uses: actions/cache/restore@v4
      with:
        path: ~/apt-archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Dependencies (Dry Run)
      run: npx playwright install-deps chromium --dry-run
    - name: Set package variable from dry run
      id: packages
      run: echo "PACKAGES=$(npx playwright install-deps chromium --dry-run | grep -oP '(?<=install -y --no-install-recommends ).*[^"]')" >> $GITHUB_OUTPUT
    - name: Create apt archives partial directory
      run: mkdir -p ~/apt-archives/partial
    - name: Download apt packages
      run: sudo apt-get update && sudo apt-get install --download-only -o Dir::Cache::Archives=~/apt-archives ${{ steps.packages.outputs.PACKAGES }}
    - name: Save apt archives cache
      uses: actions/cache/save@v4
      if: steps.cache-apt.outputs.cache-hit != 'true'
      with:
        path: ~/apt-archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/package-lock.json') }}
    - name: Install apt packages from cache
      run: sudo apt-get install -o Dir::Cache::Archives=~/apt-archives ${{ steps.packages.outputs.PACKAGES }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Run Auth Secret
      run: npx auth secret
    - name: Run Playwright tests
      run: npx playwright test --project=chromium
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
